# Replace "changeme" values before deploying.
apiVersion: v1
kind: Secret
metadata:
  name: configiq-credentials
  namespace: psap-configiq
type: Opaque
stringData:
  aiconfigurator-username: "rh-admin"
  aiconfigurator-password: "TKuquV42nZADo69"
  gpu-sizer-username: "rh-admin"
  gpu-sizer-password: "TKuquV42nZADo69"
